services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.post
    container_name: ${POSTGRES_HOST:-postgres}
    restart: always
    env_file:
      - .env
      - .env.local
    networks:
      - ${POSTGRES_NETWORK_NAME:-postgres_net}  
    ports:
      - "${POSTGRES_EXT_PORT}:5432"
    volumes:
      - ./postgres/initdb:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
      - ./backup:/backup
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: ${PGADMIN_CONTAINER_NAME:-pgadmin}
    restart: always
    env_file:
      - .env
      - .env.local
    ports:
      - "${PGADMIN_EXT_PORT:-80}:80"
    user: root
    entrypoint: /bin/sh -c "chmod 600 /pgadmin4/pgpass; /entrypoint.sh;"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./backup:/var/lib/pgadmin/storage
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/pgpass:/pgadmin4/pgpass
    networks:
      postgres_net:
    depends_on:
      - postgres
networks:
  postgres_net:
    name: postgres_net

volumes:
  postgres_data:
  pgadmin_data:
