services: 
  mqtt:
    container_name: ${MQTT_CONTAINER_NAME:-mqtt}
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - postgres_network
    env_file:
      - ../.env
      - ../.env.local

networks:
  postgres_net:
    external: true