services: 
  mqtt:
    container_name: ${MQTT_CONTAINER_NAME}
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
      - .env.local

networks:
  postgres_net:
    external: true